In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [41]:
data = pd.read_csv('Churn_Modelling.csv')

In [42]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [43]:
X = data.iloc[:,3:13].values
Y = data.iloc[:,13].values

In [44]:
Y

array([1, 0, 1, ..., 1, 1, 0])

# Encoding Categorical Data 

In [45]:
label_encoder_X_1 = LabelEncoder()
X[:,1] = label_encoder_X_1.fit_transform(X[:,1])

In [46]:
label_encoder_X_2 = LabelEncoder()
X[:,2] = label_encoder_X_2.fit_transform(X[:,2])

In [47]:
one_hot_encoder = OneHotEncoder(categorical_features=[1])
X = one_hot_encoder.fit_transform(X).toarray()

 ## Tran-Test split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Feature Scaling

In [49]:
sc = StandardScaler()

In [50]:
X_train = sc.fit_transform(X_train)

In [51]:
X_test = sc.transform(X_test)

## Initialize ANN

In [27]:
classifier = Sequential()

## Add Layers

In [32]:
# input layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))
# hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
# output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

## Compiling the ANN 

In [33]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

## Fitting The ANN to  the training set

In [35]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.5081 - acc: 0.7945
Epoch 2/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.5081 - acc: 0.7945
Epoch 3/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.5081 - acc: 0.7945
Epoch 4/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.5081 - acc: 0.7945
Epoch 5/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.5081 - acc: 0.7945
Epoch 6/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.5081 - acc: 0.7945
Epoch 7/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.5081 - acc: 0.7945
Epoch 8/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.5081 - acc: 0.7945
Epoch 9/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.5081 - acc: 0.7945
Epoch 10/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.5080 - acc: 0.7945

8000/8000 [==============================] - 1s 101us/step - loss: 0.5081 - acc: 0.7945
Epoch 83/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.5081 - acc: 0.7945
Epoch 84/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.5081 - acc: 0.7945
Epoch 85/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.5081 - acc: 0.7945
Epoch 86/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.5081 - acc: 0.7945
Epoch 87/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.5082 - acc: 0.7945
Epoch 88/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.5081 - acc: 0.7945
Epoch 89/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.5081 - acc: 0.7945
Epoch 90/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.5081 - acc: 0.7945
Epoch 91/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.5081 - acc: 0.7945
Epoch 

## Evaluate and Prediction

In [36]:
y_pred = classifier.predict(X_test)

In [52]:
y_pred = (y_pred > .5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [53]:
cm = confusion_matrix(y_test,y_pred)

In [54]:
cm

array([[1607,    0],
       [ 393,    0]])

In [56]:
# Accuracy
(1607 + 0)/2000

0.8035